repos:
-   repo: local
    hooks:
        #   - id: isort
        #     name: isort
        #     entry: isort .
        #     types: [python]
        #     language: system

    - id: black
      name: black
      entry: black .
      language: system
      types: [python]
