[tool.poetry]
name = "openpype-server"
version = "4.0.0"
description = ""
authors = ["Martastain <martas@imm.cz>"]

[tool.poetry.dependencies]
python = "^3.10"
nxtools = "^1.6"
orjson = "^3.6.7"
fastapi = "^0.73.0"
strawberry-graphql = {extras = ["fastapi"], version = "^0.97.0"}
uvicorn = {extras = ["standard"], version = "^0.17.5"}
aioredis = "^2.0.1"
asyncpg = "^0.25.0"
email-validator = "^1.1.3"
httpx = "^0.22.0"
pytest-order = "^1.0.1"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
black = {version = "^22.1.0", allow-prereleases = true}

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
