[tool.poetry]
name = "ayon-server"
version = "1.0.0"
description = ""
authors = ["Ynput <info@ynput.io>"]

[tool.poetry.dependencies]
python = "^3.10"
codenamize = "^1.2.3"
email-validator = "^1.1.3"
geoip2 = "^4.6.0"
nxtools = "^1.6"
psutil = "^5.9.4"
strawberry-graphql = {extras = ["fastapi"], version = "^0.158.1"}
toml = "^0.10.2"
types-toml = "^0.10.8"
user-agents = "^2.2.0"
uvicorn = {extras = ["standard"], version = "^0.20.0"}
asyncpg = "^0.27.0"
fastapi = "^0.92.0"
httpx = "^0.23.3"
orjson = "^3.8.6"
redis = "^4.5.1"
yaoauth2 = "^1.1"
aiofiles = "^23.1.0"

[tool.poetry.dev-dependencies]
pytest = "^7.0.0"
pytest-order = "^1.0.1"
black = {version = "^22.1.0", allow-prereleases = true}
isort = "^5.10.1"
flake8 = "^4.0.1"
mypy = "^0.991"
pre-commit = "^2.20.0"

[tool.isort]
profile = "black"
skip = ["addons/"]

[tool.black]
line-length = 88

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

